<footer class="container-fluid col-xs-12 footer">
	<div class="col-xs-12 col-sm-4">
		<ul>
			<li><h5>Pages</h5>
				<ul>
					<li><a href="index.php">Home</a></li>
					<li><a href="afspraakFormulier.php">Afspraak maken</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-4">
		<ul>
			<li><h5>Contact</h5>
				<ul>
					<li>Rue de la Bouteille 65</li>
					<li>291105 VP Bordeaux, Frankrijk</li>
					<li>079-232 44 11 55</li>
					<li><a href="mailto:gemeentebordeaux%40gmail%2Ecom">GemeenteBordeaux&#64;gmail&#46;com</a></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="col-xs-12 col-sm-4">
		<ul class="inline">
			<li><h5>Social</h5>
				<ul>
					<li><span class="sr-only">Facebook</span> <a href="https://www.facebook.com/places/Dingen-die-je-kunt-doen-in-Bordeaux-stad/115838035093755/"><span class="flaticon-facebookicon" aria-hidden="true"></span></a></li>
					<li><span class="sr-only">Youtube</span> <a href="http://www.youtube.com"><span class="flaticon-youtubeicon" aria-hidden="true"></span></a></li>
					<li><span class="sr-only">Twitter</span> <a href="https://twitter.com/search?q=Bordeaux&src=tyah&lang=nl"><span class="flaticon-twittericon" aria-hidden="true"></span></a></li>
					<li><small>Font (icons) generated by <a href="http://www.flaticon.com">flaticon.com</a>, <a href="http://www.flaticon.com/authors/linh-pham">facebook & twitter icons made by Linh Pham</a>, <a href="http://www.flaticon.com/authors/alessio-atzeni">youtube icon made by Alessio Atzeni</a></small></li>
				</ul>
			</li>
		</ul>
	</div>
	<div class="col-xs-12">
		<div class="col-xs-4"></div>
		<div class="col-xs-4 text-center">&copy;Copyright De YaKai</div>
	</div>
</footer>